#!/bin/bash

PACKS=("ancestries" "ancestryfeatures" "feats" "heritages")

for pack in ${PACKS[@]};
do
    npx fvtt package unpack ${pack} --id "calamity-in-ouroboros" --type "Module" --in data/Data/modules/calamity-in-ouroboros/packs --out src/packs/${pack} --yaml
done
