#!/bin/bash

PACKS=("ancestries" "ancestryfeatures" "feats" "heritages")

for pack in ${PACKS[@]};
do
    npx fvtt package pack ${pack} --id "calamity-in-ouroboros" --type "Module" --in src/packs/${pack} --out data/Data/modules/calamity-in-ouroboros/packs --yaml
done
