#!/bin/bash

npx fvtt package unpack "ancestries" --id "calamity-in-ouroboros" --type "Module" --in packs --out src/packs/ancestries --yaml
npx fvtt package unpack "ancestryfeatures" --id "calamity-in-ouroboros" --type "Module" --in packs --out src/packs/ancestryfeatures --yaml
npx fvtt package unpack "feats" --id "calamity-in-ouroboros" --type "Module" --in packs --out src/packs/feats --yaml
npx fvtt package unpack "heritages" --id "calamity-in-ouroboros" --type "Module" --in packs --out src/packs/heritages --yaml
