#!/bin/bash

PACKS=("ancestries" "ancestryfeatures" "heritages")

for pack in ${PACKS[@]};
do
    npx fvtt package pack ${pack} --id "calamity-in-ouroboros" --type "Module" --in src/packs/${pack} --out packs --yaml
done
