#!/bin/bash

PACKS=("ancestries" "ancestryfeatures" "heritages")

for pack in ${PACKS[@]};
do
    npx fvtt package unpack "${pack}" --id "calamity-in-ouroboros" --type "Module" --in packs --out src/packs/${pack} --yaml
done
